server:
  port: 8080
  servlet:
    context-path:
  tomcat:
    max-http-post-size: -1
spring:
  #出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)
  mvc:
    throw-exception-if-no-handler-found: true
  #不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false
  application:
    name: switcher
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 600MB

  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dk_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #     数据源其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #     配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  #pagehelper:
  #  helper-dialect: mysql
  #  reasonable: true
  #  supportMethodsArguments: true
  #  params: count=countSql

  #  redis配置，需要一个配置类来读取
  redis:
    database: 12
    timeout: 1000
    # Redis服务器地址
    host: 192.168.3.50
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 1234mima
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1024
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池中的最小空闲连接
        min-idle: 0
thread:
  core-pool-size: 10            # 核心线程数（默认线程数）
  max-pool-size: 100            # 最大线程数
  keep-alive-time: 10           # 允许线程空闲时间（单位：默认为秒）
  queue-capacity: 200           # 缓冲队列数
  name-prefix: Async-Service-   # 线程池名前缀

#mybatis mapping文件位置配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

#  自定义属性
redis:
  pattern-topic: __keyevent@11__:expired